// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZQ-puQcIAka-mcJ3I3GOKakfS-ip3e8I',
    appId: '1:810953460152:web:687049623efc2312dca74d',
    messagingSenderId: '810953460152',
    projectId: 'bus-seva-6144e',
    authDomain: 'bus-seva-6144e.firebaseapp.com',
    storageBucket: 'bus-seva-6144e.firebasestorage.app',
    measurementId: 'G-433ZXECGFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0BVZB5dBoLnJakjTKhe4K2re9SqDlYA',
    appId: '1:810953460152:android:3cd4d033572b377cdca74d',
    messagingSenderId: '810953460152',
    projectId: 'bus-seva-6144e',
    storageBucket: 'bus-seva-6144e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBo8MnAOdcm7Yd_m5wjR5fmh2mH-qHx3Y',
    appId: '1:810953460152:ios:f6ba6f06dd65fbb1dca74d',
    messagingSenderId: '810953460152',
    projectId: 'bus-seva-6144e',
    storageBucket: 'bus-seva-6144e.firebasestorage.app',
    iosBundleId: 'in.gov.busseva.driver',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBo8MnAOdcm7Yd_m5wjR5fmh2mH-qHx3Y',
    appId: '1:810953460152:ios:49f352478e57d795dca74d',
    messagingSenderId: '810953460152',
    projectId: 'bus-seva-6144e',
    storageBucket: 'bus-seva-6144e.firebasestorage.app',
    iosBundleId: 'com.busseva.busseva1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZQ-puQcIAka-mcJ3I3GOKakfS-ip3e8I',
    appId: '1:810953460152:web:763782fe30a5c6cfdca74d',
    messagingSenderId: '810953460152',
    projectId: 'bus-seva-6144e',
    authDomain: 'bus-seva-6144e.firebaseapp.com',
    storageBucket: 'bus-seva-6144e.firebasestorage.app',
    measurementId: 'G-4ETY425W0L',
  );

}