build-ios:
  name: Build iOS App
  runs-on: macos-latest

  steps:
    - uses: actions/checkout@v4

    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.35.3'

    - name: Install CocoaPods
      run: |
        sudo gem install cocoapods ffi
        pod repo update

    - name: Cache CocoaPods
      uses: actions/cache@v3
      with:
        path: ios/Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('ios/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - run: flutter pub get

    - name: Install iOS pods
      run: |
        cd ios
        rm -rf Pods Podfile.lock
        pod install --repo-update
        cd ..

    - name: Build iOS app (no codesign)
      run: flutter build ios --release --no-codesign

    - name: Create iOS Archive
      run: |
        mkdir -p ios_build
        cp -r build/ios/iphoneos/Runner.app ios_build/
        cd ios_build
        zip -r ios-app-release.zip Runner.app

    - name: Upload iOS App
      uses: actions/upload-artifact@v4
      with:
        name: ios-app-release.zip
        path: ios_build/ios-app-release.zip
